### ISSUE TITLE
Crashing Ableton

### ISSUE THREAD

**Issue by Chinguaga** [Bloodbat/SanguineMutants#8]
hey ho. love ur modules sadly they are crashing my ableton on startup. Let me know what data i need to provide u in order 2 help.

Ableton 10 10.1.43
Rack Pro 2.5.2
Windows Version	10.0.19045 Build 19045

Btw Polyphonic Clouds Grains would fit the universe well :)

Cheers

**Comment by Bloodbat** [comment]
Hey ho, let's go!

Thanks for the comments :)

Some useful info:

- What's your video card?
- What's the plugin version?
-Did you get it from the Rack Library, Github or did build it yourself?
-You mention it crashes on start-up, is this right after creating an empty Rack or loading an existing patch?
-If it was an existing patch, were my modules the only ones in that patch?
-Mind if I take a look at the Ableton log?

A polyphonic version of Clouds is provided by Surge XT, you may wanna take a look at it, if you haven't already, it's called Nimbus.

Best regards :)

**Comment by Chinguaga** [comment]
Hi thanks for your quick reply and the module tip haha ;D

   * What's your video card?
NVIDIA GeForce RTX 2080 Super. ( some old driver ) 
   * What's the plugin version?
  2.3.0
   * Did you get it from the Rack Library, Github or did build it yourself?
   The Rack Library
   * You mention it crashes on start-up, is this right after creating an empty Rack or loading an existing patch?
1. I start Ableton and build a crazy patch with ur modules
2. I save and call it a day
3. I reload the project on another day
4. it will crash
5. only fix is to load all tracks into a new project without vcv
    * This crash will occur if i load a sole single one of ur modules into vcv. Save. and Restart Ableton.
    * I checked its not happening with stock modules or other 3rd party modules.( I have the feeling that other modules might cause the issue 2 but i cant test them all).
  * If it was an existing patch, were my modules the only ones in that patch?
 Yes 
  * Mind if I take a look at the Ableton log?
I attached but im also GitHub Noob. Hope it works

[Ableton Crash Report 2024-09-27 223702 Live 10.1.43.zip](https://github.com/user-attachments/files/17169518/Ableton.Crash.Report.2024-09-27.223702.Live.10.1.43.zip)

**Comment by Bloodbat** [comment]
You're welcome :)

The log attached fine,  I'll take a look at it; but the first step I recommend is updating the plugin: considering you are posting in the Mutants repository, I'm guessing those are the ones that crash, the current version is 2.4.1. (The library version is 2.4.1. The Sanguine Monsters are, indeed, 2.3.0)
The 2.3.0 Mutants had a known crash (well, not to me, for some magical reason it didn't die on my machine, but someone thankfully pointed it out) due to some stuff I forgot to restore when dealing with alternative firmwares.
If we're talking about the Monsters (those are at version 2.3.0, indeed), that's a different respository; but it's all right, just so I know what we're talking about (and, as stated, the 2.3.0 Mutants did, indeed, have a crash).

**Comment by Bloodbat** [comment]
Related to #6

**Comment by Bloodbat** [comment]
Oh wow, that's a bit surprising; but quite helpful.

Thanks for reporting about the Monsters as well. I'll look into them.

I've gathered other reports of the Mutants problem.

I've been doing quite a deep dive into the Mutants trying to fix this. There have been some changes to Anuli that might fix the problem, if you're willing to test the Nightly builds.

If you are, make sure ONLY one module is present (e.g. Anuli) so that if the problem remains it can be isolated and we can be sure it's a Mutant and not something else. Also, if you do test the nightlies, ensure you restart your machine before doing so: current CPUs and OSes achieve their speed using a number of techniques, but can keep offending code cached and ignore the fixes: that has bitten me more than once :)

**Comment by Bloodbat** [comment]
The crashes have been solved, you can wait for the Library release that includes the fixes; I will drop a release containing them ASAP (and post a notice here), or you can try a Nightly, using the instructions above, the Bugbusters will be deleted.

**Comment by Bloodbat** [comment]
The 2.4.2 release with the fixes is available here:

https://github.com/Bloodbat/SanguineMutants/releases/tag/2.4.2

Thanks for reporting :)

**Comment by Chinguaga** [comment]
Hey ho so ur the fix successfully updated the Mutants to 2.4.2 and fixed the bug. Nice !
However it dit not update the monsters that remain on 2.3.0 .they still crash ;)

**Comment by Bloodbat** [comment]
The Monsters also have an updated build available with the fixes
https://github.com/Bloodbat/SanguineMonsters/releases/tag/2.3.1

Thanks for reporting the bugs :)

**Comment by Chinguaga** [comment]
ah nice so i got the update via vcv module library auto update in the aplication and it worked and fixed it. so now everything is working. thx

I have an idea for you. In MAX and Supercolider therer is Multichannel audio and every knob of an "effect" can be set to a distribution of values that differ on every channel. Thus u can modulate every channel differently. Or you could feed a Multichannel LFO to an Input of one of your modules and This way one could get multichannel modulation. Just an idea ^^ would be realy unique in vcv world

**Comment by Bloodbat** [comment]
I'm glad everything is working now :)

As for your suggestion, are there any videos out there of what you're suggesting in action? So I can see what it does / how it works?

From what I understand, correct me if I'm wrong: the signal from a single LFO gets fed to a sort of randomizer module; that randomizer module turns a single channel signal into a *n* channel polyphonic one, with a certain amount of randomization added to every channel; the output, polyphonic signal can then be used to modulate either a single module or split to modulate several?

**Comment by Chinguaga** [comment]
![grafik](https://github.com/user-attachments/assets/5e1f01e1-a03d-407e-b4ca-4b054f53b091)
 This is inspired by an omri cohen video. Sadly i cant send u the patch on Github as it doesnt accept the file type.
 
 Basically This is a Polyphonic Arpegiator into a Polyphonic OSCilator. The 4 channels get send through Rings and then get downsampled into a stereo signal. The downsampling does apply some interesting spacialisation.

I read a liddle bit into your manual. so u state that its basically an instance of rings for each channel. where all instances have the same settings. In the patch above it would be quite interesting to have different settings of rings on every channel.

1.)
What MAX MSP allows is to do stuff like this. For a single Parameter. user picks a value. 
That value is multiplied with a harmonc series across the instances of rings. Thus the same parameter has different values on every other multichannel isntance of RIngs.

More streight foreward is to take the user chosen value and add some random values within a spefic Range onto the other instacnes.


2.) 
also in Max u can just send a Multichannel Signal into each Parameter of a Multichannel Object. In this case sending a Polyphonc Modulator Signal into for instance Frequency. 


I hope i explained it well enough ;D;D but yea sounds like work ;DD;D

**Comment by Bloodbat** [comment]
I probably saw the video; but can you post the link anyway?

Different Anuli modes for every channel using the same module is in the nightlies; other than that, practically every parameter (except for "polyphony") can be different for every channel in the version you already have, just send enough signals.

![Screenshot 2024-10-06 145644](https://github.com/user-attachments/assets/d2ae0945-f547-48c1-9b29-12d9da04765b)

"That value is multiplied with a harmonc series across the instances of rings. Thus the same parameter has different values on every other multichannel isntance of RIngs." This job is best left to an external module.

"Also in Max u can just send a Multichannel Signal into each Parameter of a Multichannel Object. In this case sending a Polyphonc Modulator Signal into for instance Frequency." already doable... just try it.

Understanding how Anuli (and Rings) work is important for this to work, though: you need a Strum, V/Oct and In for every channel you want, or trust Anuli to do it and leave certain inputs unpatched. Whatever is patched expects some signal in the corresponding channel.

[anuli_poly_demo.zip](https://github.com/user-attachments/files/17270912/anuli_poly_demo.zip)

You can zip patches and upload them here, BTW.
